server:
  port: 9090

spring:
  application:
    name: Product-Command-Service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
  zookeeper:
    connect-string: localhost:2181
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: root
    password: rootUser@123
    driver-class-name: com.mysql.cj.jdbc.Driver
