server:
  port: 9091

spring:
  application:
    name: Product-Query-Service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
  zookeeper:
    connect-string: localhost:2181
  datasource:
    url: jdbc:mysql://localhost:3307/your_database_name
    username: root
    password: rootUser@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MYSQLDialect